package com.whty.tathing.enterfront.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-11-25T10:16:56.874+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://www.tathing.com", name = "IEnterFrontService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IEnterFrontService {

    @WebResult(name = "AppPersonialResponse", targetNamespace = "http://www.tathing.com", partName = "AppPersonialResponse")
    @WebMethod(operationName = "AppPersonial")
    public AppPersonialResponse appPersonial(
        @WebParam(partName = "AppPersonialRequest", name = "AppPersonialRequest", targetNamespace = "http://www.tathing.com")
        AppPersonialRequest appPersonialRequest
    );

    @WebResult(name = "CreatSSDResponse", targetNamespace = "http://www.tathing.com", partName = "CreatSSDResponse")
    @WebMethod(operationName = "CreatSSD")
    public CreatSSDResponse creatSSD(
        @WebParam(partName = "CreatSSDRequest", name = "CreatSSDRequest", targetNamespace = "http://www.tathing.com")
        CreatSSDRequest creatSSDRequest
    );

    @WebResult(name = "AppStatusNotifyResponse", targetNamespace = "http://www.tathing.com", partName = "AppStatusNotifyResponse")
    @WebMethod(operationName = "AppStatusNotify")
    public AppStatusNotifyResponse appStatusNotify(
        @WebParam(partName = "AppStatusNotifyRequest", name = "AppStatusNotifyRequest", targetNamespace = "http://www.tathing.com")
        AppStatusNotifyRequest appStatusNotifyRequest
    );

    @WebResult(name = "PublicKeyResponse", targetNamespace = "http://www.tathing.com", partName = "PublicKeyResponse")
    @WebMethod(operationName = "PublicKey")
    public PublicKeyResponse publicKey(
        @WebParam(partName = "PublicKeyRequest", name = "PublicKeyRequest", targetNamespace = "http://www.tathing.com")
        PublicKeyRequest publicKeyRequest
    );

    @WebResult(name = "AppDownloadResultNotifyResponse", targetNamespace = "http://www.tathing.com", partName = "AppDownloadResultNotifyResponse")
    @WebMethod(operationName = "AppDownloadResultNotify")
    public AppDownloadResultNotifyResponse appDownloadResultNotify(
        @WebParam(partName = "AppDownloadResultNotifyRequest", name = "AppDownloadResultNotifyRequest", targetNamespace = "http://www.tathing.com")
        AppDownloadResultNotifyRequest appDownloadResultNotifyRequest
    );

    @WebResult(name = "AppDeleteResultNotifyResponse", targetNamespace = "http://www.tathing.com", partName = "AppDeleteResultNotifyResponse")
    @WebMethod(operationName = "AppDeleteResultNotify")
    public AppDeleteResultNotifyResponse appDeleteResultNotify(
        @WebParam(partName = "AppDeleteResultNotifyRequest", name = "AppDeleteResultNotifyRequest", targetNamespace = "http://www.tathing.com")
        AppDeleteResultNotifyRequest appDeleteResultNotifyRequest
    );

    @WebResult(name = "AppPushResponse", targetNamespace = "http://www.tathing.com", partName = "AppPushResponse")
    @WebMethod(operationName = "AppPush")
    public AppPushResponse appPush(
        @WebParam(partName = "AppPushRequest", name = "AppPushRequest", targetNamespace = "http://www.tathing.com")
        AppPushRequest appPushRequest
    );

    @WebResult(name = "SSDInfoResponse", targetNamespace = "http://www.tathing.com", partName = "SSDInfoResponse")
    @WebMethod(operationName = "SSDInfo")
    public SSDInfoResponse ssdInfo(
        @WebParam(partName = "SSDInfoRequest", name = "SSDInfoRequest", targetNamespace = "http://www.tathing.com")
        SSDInfoRequest ssdInfoRequest
    );

    @WebResult(name = "AppDownloadResponse", targetNamespace = "http://www.tathing.com", partName = "AppDownloadResponse")
    @WebMethod(operationName = "AppDownload")
    public AppDownloadResponse appDownload(
        @WebParam(partName = "AppDownloadRequest", name = "AppDownloadRequest", targetNamespace = "http://www.tathing.com")
        AppDownloadRequest appDownloadRequest
    );

    @WebResult(name = "AppDeleteResponse", targetNamespace = "http://www.tathing.com", partName = "AppDeleteResponse")
    @WebMethod(operationName = "AppDelete")
    public AppDeleteResponse appDelete(
        @WebParam(partName = "AppDeleteRequest", name = "AppDeleteRequest", targetNamespace = "http://www.tathing.com")
        AppDeleteRequest appDeleteRequest
    );

    @WebResult(name = "TokenSignResponse", targetNamespace = "http://www.tathing.com", partName = "TokenSignResponse")
    @WebMethod(operationName = "TokenSign")
    public TokenSignResponse tokenSign(
        @WebParam(partName = "TokenSignRequest", name = "TokenSignRequest", targetNamespace = "http://www.tathing.com")
        TokenSignRequest tokenSignRequest
    );

    @WebResult(name = "AppActiveResponse", targetNamespace = "http://www.tathing.com", partName = "AppActiveResponse")
    @WebMethod(operationName = "AppActive")
    public AppActiveResponse appActive(
        @WebParam(partName = "AppActiveRequest", name = "AppActiveRequest", targetNamespace = "http://www.tathing.com")
        AppActiveRequest appActiveRequest
    );

    @WebResult(name = "OrderSaveResponse", targetNamespace = "http://www.tathing.com", partName = "OrderSaveResponse")
    @WebMethod(operationName = "OrderSave")
    public OrderSaveResponse orderSave(
        @WebParam(partName = "OrderSaveRequest", name = "OrderSaveRequest", targetNamespace = "http://www.tathing.com")
        OrderSaveRequest orderSaveRequest
    );
}
